config/routes.rb
Rails.application.routes.draw do
  get 'timetable/index'

  get 'list/index'

  get 'song/index'

  devise_for :members

  root to: "song#index"
  post "/song/play" => "song#play", as: :song_play
  post "list/index" => "list#index"
  post "timetable/index" => "timetable#index"

end

app/models/fav.rb
class Fav < ActiveRecord::Base
  belongs_to :list
  belongs_to :song
  belongs_to :member
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :member
  belongs_to :song
  has_many :timetable

  #validates :member_id, uniqueness: { scope: [:song_id]}
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :lists
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_many :lists
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
	belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
  	@lists = List.where(:member_id => current_member)
  end
end

app/controllers/song_controller.rb
class SongController < ApplicationController
	 def index
	 	#binding.pry
	  		@songs = Song.all
	  end
	  def play

		  	@list = List.create(member_id: current_member.id, song_id: params[:foo])
		  		#binding.pry
				
			if @list.valid?
				@time = Timetable.new
		    	@time.playtime = Time.now.in_time_zone("Eastern Time (US & Canada)")
				@time.list = @list
				@time.save


		  	end
	  end
end

app/controllers/timetable_controller.rb
class TimetableController < ApplicationController
  def index
  	@tests = List.joins(:timetable).where(:member_id => current_member.id).group(:song_id).count
    @tests1 = List.joins(:timetable).where(:member_id => current_member.id).group(:song_id)
  	#binding.pry
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/timetable_helper.rb
module TimetableHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Striped</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>

<header >
	<div class= 'container'>
      <div class= "span-24 colborder" id="sidebar"  >
      	<h3>LASTfm</h3>
      </div>
          

          <div class= 'box'>
          	<div class='quiet'>

          	<div class ='span-2'> <li><%= link_to "Home" , song_index_path %></li></div>
             <% if member_signed_in? %>
            <li><%= link_to "Sign Out", destroy_member_session_path, :method => :delete %></li>
            	<% else %>
			<li><%= link_to "Log in", new_member_session_path %></li>
			<% end %>
		
		</div>
          </div>
        
      </div>
    
      
        
        
          <%= yield %>
       


    </header>
<%= mp3_player_headers %>


</body>
</html>

app/views/list/index.html.erb
<% if member_signed_in? %>

<table class="table">
	<tr><td><b>Songname</b></td>
	<td><b>Album</b></td>
	<td><b>Artist</b></td>
	</tr>
		<% @lists.each do |a| %>
		<tr>
		<td ><%= a.song.songname %></td>
		<td ><%= a.song.album %></td>
		<td ><%= a.song.artist %></td>

		</tr>
		<% end %>

</table>

<% else %>
<h2><em>Please login or signup</em></h2>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/song/index.html.erb
<% if member_signed_in? %>
<h1>List of songs</h1>

<class="btn-default"><%= button_to "Recently played", list_index_path %>
<br>
<class="btn-default"><%= button_to "Most played", timetable_index_path %> 

<hr>
<table class="table table-hover">
	<tr><td><b>Songname</b></td>
	<td><b>Artist</b></td>
	<td><b>Album</b></td>
	<td><b>Duration</b></td>
	<td><b>Playnow</b></td>
	<td><b>Favorite</b></td></tr>

	
<% @songs.each do |a| %>
<tr>
<td ><%= a.songname %></td>
<td ><%= a.artist %></td>
<td > <%= a.album %></td>
<td ><%= a.duration %></td>
<td class="btn-default"><%= button_to "Play", song_play_path(foo: a.id) %></td>
<td class="warning"><%= radio_button :autolyse, false, :checked => true %></td>
</tr>

<% end %>
</table>
<% else %>

<h2><em>Please login or signup</em></h2>
<% end %>

app/views/song/play.html.erb
Playing song

<%= mp3_player("http://github.com/sekrett/mp3_player/raw/master/test.mp3") %>

app/views/timetable/index.html.erb
<% if member_signed_in? %>

<table class="table table-hover">
		<tr><td><b>Song name</b></td>
	<td><b>Favourite</b></td>
	<td><b>Number of times played</b></td>
	</tr>
	<tr>
		<td>
			<table class="table table-hover">
				<% @tests1.each do |a| %>
				<tr><td class="success"> <%= a.song.songname %></td></tr>
				<% end %>

			</table>
		</td>
		<td>
			
		</td>
		<td>
			<table class="table table-hover">
				<% @tests.each do |key, value| %>
				<tr><td class="danger"> <%= value %></td></tr>
				<% end %>
			</table>
		</td>
		
	</tr>

	</table>
<% else %>
<h2><em>Please login or signup</em></h2>
<% end %>